### ISSUE TITLE
Hello! 

### ISSUE THREAD

**Issue by nousiaso** [Gabaldonlab/perSVade#1]
First of all congratulations for the awesome pipeline!

When I try to annotate the integrated SVs_CNVs using a gff i get an error 

 File "/perSVade/scripts/sv_functions.py", line 691, in run_cmd
    if out_stat!=0: raise ValueError("\n%s\n did not finish correctly. Out status: %i"%(cmd_to_run, out_stat))

I have checked the gff, with the gff3 validator. It should not be the problem..

also i take a look at the tmp file from the annotations and this is the error it outputs

"Use of uninitialized value $key in hash element at /opt/conda/envs/perSVade_env/share/ensembl-vep-100.2-0/Bio/EnsEMBL/IO/Parser/GFF3.pm line 195, <__ANONIO__> line 675.
Can't call method "strand" on unblessed reference at /opt/conda/envs/perSVade_env/share/ensembl-vep-100.2-0/modules/Bio/EnsEMBL/VEP/AnnotationType/Transcript.pm line 102, <__ANONIO__> line 675."

I can attach you some txt files if you need them

Looking forward to your reply
Orestis

**Comment by nousiaso** [comment]
Actually i think i have found the solution

https://github.com/Ensembl/ensembl-vep/issues/70

it has to do with some lines in gff strand column 7 do not have the right symbol they have . instead of + or -

**Comment by nousiaso** [comment]
This is something connected to VEP, and should not concern RERSVADE. Alghough you might leave it here for information purposes

**Comment by nousiaso** [comment]
Ultimately I was able to find a solution, it was the same as https://github.com/Ensembl/ensembl-vep/issues/70 having "." in the place of strand in some features of stringtie annotation

**Comment by MikiSchikora** [comment]
Hi,

I am happy that you could solve the issue. It is usually tricky to work for gffs, so that your solution is very useful for the future! I will implement a check of the strand in the annotation modules, so that it is easier to debug.
