### ISSUE TITLE
C_ALL: cannot change locale (en_US.UTF-8): No such file or directory

### ISSUE THREAD

**Issue by xibeixingchen** [Gabaldonlab/perSVade#11]
Hi,

I restarted the unbuntu server, using code commands, like  `singularity exec -e /home/jiazc/software/persvade_v1.sif bash -c 'source /opt/conda/etc/profile.d/conda.sh && conda activate perSVade_env && python /perSVade/scripts/perSVade call_SVs --ref /home/jiazc/work/alfalfa_genome/Muxu_Genome_Final_filter.fasta --mitochondrial_chromosome no_mitochondria --SVcalling_parameters /home/jiazc/work/persvade_output/parameter_optimization_random/optimized_parameters.json --repeats_file skip --verbose --fraction_available_mem 0.3 --threads 16 -o /home/jiazc/work/persvade_output/B186/call_SVs -sbam /home/jiazc/work/persvade_output/B186/aligned_reads/aligned_reads.bam.sorted'` .but there was an error. 
How can I fix it.
[aligned_reads.bam.sorted.generating.txt](https://github.com/Gabaldonlab/perSVade/files/10097406/aligned_reads.bam.sorted.generating.txt)

Thanks ,
Best,
Jia

**Comment by MikiSchikora** [comment]
Hi,

Can you attach the full log of perSVade? I can't see the error now.

Best,
Miquel Àngel Schikora

**Comment by MikiSchikora** [comment]
Hi,

Is this solved? If so you may close this issue.

Best,
Miquel Àngel Schikora

**Comment by MikiSchikora** [comment]
Hi,
Is this solved? I'd close the issue if so.

Miquel Àngel Schikora
Barcelona Supercomputing Center
