### ISSUE TITLE
Issue with the repeat_inference

### ISSUE THREAD

**Issue by guidopuccetti** [Gabaldonlab/perSVade#15]
Dear Miquel,

I am having an issue with the mounting point, which I previously did not encounter and I would like your opinion.

Currently this is the script I am running
sbatch -c 16 --wrap="docker run -v /data4/guido/perSVade:/reference_genome_dir -v /data4/guido/perSVade:/output_directory mikischikora/persvade:v1.02.6 python -u ./scripts/perSVade infer_repeats -o /output_directory/repeat_inference -r /reference_genome_dir/reference_genome.fasta --fraction_available_mem 0.20"

The error I get is the following but unfortunately is not really informative
```
### SLURM JOB STATS ########################
#
#
### SLURM JOB OUTPUT ########################
Running module infer_repeats...
ERROR conda.cli.main_run:execute(34): Subprocess for 'conda run ['python', '-u', './scripts/perSVade', 'infer_repeats', '-o', '/output_directory/repeat_inference', '-r', '/reference_genome_dir/reference_genome.fasta', '-thr', '16', '--fraction_available_mem', '0.20']' command failed.  (See above for error)
```
Since I am still not yet really familiar with Docker, I am really curious to hear from you! Thanks!

**Comment by MikiSchikora** [comment]
Hi,

If I understand correctly, you are mounting the folder `/data4/guido/perSVade` of the host into two different folders inside the container `/output_directory` and `/reference_genome_dir` right? This may be the source of the problem, and it could be solved by mounting once. For instance:
 
 `docker run -v /data4/guido/perSVade:/perSVade_run mikischikora/persvade:v1.02.6 python -u ./scripts/perSVade infer_repeats -o /perSVade_run/repeat_inference -r /perSVade_run/reference_genome.fasta --fraction_available_mem 0.20`
 
Does this make sense? I'd recommend testing this outside of slurm running, just as a single command to verify that the pipeline starts. If the problem persists, could you send me the full log?

Best,

Miquel Àngel Schikora
 
PS: I see that such commands may be confusing, and we are working on an easier wrapper for future versions, that automatically handles mounting and docker/singularity runs. However, this is still a work in progress.

**Comment by MikiSchikora** [comment]
Good morning,

Is this solved? I'd close the issue if so.

Best,
Miquel Àngel Schikora
