### ISSUE TITLE
Python installation works but trim_reads_and_QC module fails during test installation

### ISSUE THREAD

**Issue by MatteoSebastianelli** [Gabaldonlab/perSVade#21]
Hello,

I am trying to implement perSVuade on my short-read dataset. I managed to run the python installation quite smoothly, or at least so it seemed. The general and module-specific --help command work. However, when I run the test_installation_modules.py script I get the following error regarding the trim_reads_and_QC module:

######
Running the test_installation_modules.py script...
[22/11/2024, 09:11:45] loading python packages worked successfully
[22/11/2024, 09:11:45] all output files will be written to ./installation/test_installation/testing_outputs
[22/11/2024, 09:11:45] setting all the files
[22/11/2024, 09:11:45] Running modules
Running module trim_reads_and_QC...
Traceback (most recent call last):
  File "/crex/proj/snic2020-2-19/private/darwins_finches/users/seba/BIN/perSVade/installation/test_installation/../../scripts/trim_reads_and_QC", line 107, in <module>
    real_available_threads = fun.get_available_threads(opt.outdir)
  File "/crex/proj/snic2020-2-19/private/darwins_finches/users/seba/BIN/perSVade/installation/test_installation/../../scripts/sv_functions.py", line 1119, in get_available_threads
    sorted_bam = get_sorted_bam_test(reads1, reads2, genome, replace=False)
  File "/crex/proj/snic2020-2-19/private/darwins_finches/users/seba/BIN/perSVade/installation/test_installation/../../scripts/sv_functions.py", line 1072, in get_sorted_bam_test
    run_bwa_mem(r1, r2, ref_genome, outdir, bamfile, sorted_bam, index_bam, name_sample, threads=4, replace=False, MarkDuplicates=False)
  File "/crex/proj/snic2020-2-19/private/darwins_finches/users/seba/BIN/perSVade/installation/test_installation/../../scripts/sv_functions.py", line 1380, in run_bwa_mem
    check_sorted_bam_has_correct_insert_sizes(sorted_bam_tmp, replace, threads)
  File "/crex/proj/snic2020-2-19/private/darwins_finches/users/seba/BIN/perSVade/installation/test_installation/../../scripts/sv_functions.py", line 1274, in check_sorted_bam_has_correct_insert_sizes
    median_insert_size, median_insert_size_sd  = get_insert_size_distribution(sorted_bam, replace=replace, threads=threads)
  File "/crex/proj/snic2020-2-19/private/darwins_finches/users/seba/BIN/perSVade/installation/test_installation/../../scripts/sv_functions.py", line 8064, in get_insert_size_distribution
    run_cmd("%s CollectInsertSizeMetrics HISTOGRAM_FILE=%s INPUT=%s OUTPUT=%s > %s 2>&1"%(picard_exec, hist_file, sampled_bam, outfile_tmp, picard_insertSize_std), env=EnvName_picard)
  File "/crex/proj/snic2020-2-19/private/darwins_finches/users/seba/BIN/perSVade/installation/test_installation/../../scripts/sv_functions.py", line 692, in run_cmd
    if out_stat!=0: raise ValueError("\n%s\n did not finish correctly. Out status: %i"%(cmd_to_run, out_stat))
ValueError: 
source //crex/proj/snic2020-2-19/private/darwins_finches/users/seba/BIN/etc/profile.d/conda.sh && conda activate persvuade_picard_env > /dev/null 2>&1 && //crex/proj/snic2020-2-19/private/darwins_finches/users/seba/BIN/envs/persvuade_picard_env/bin/picard CollectInsertSizeMetrics HISTOGRAM_FILE=./installation/test_installation/testing_outputs/read_trimmingCglab/getting_available_threads/genome.fasta_simulating_reads/getting_reads/aligning_reads_against_genome.fasta/aligned_reads.bam.sorted.tmp.checking_correct_insertSizes/aligned_reads.bam.sorted.histogram_insertsizes.pdf INPUT=./installation/test_installation/testing_outputs/read_trimmingCglab/getting_available_threads/genome.fasta_simulating_reads/getting_reads/aligning_reads_against_genome.fasta/aligned_reads.bam.sorted.tmp.checking_correct_insertSizes/aligned_reads.bam.sorted.1pct_reads_seed172_sampleX.bam OUTPUT=./installation/test_installation/testing_outputs/read_trimmingCglab/getting_available_threads/genome.fasta_simulating_reads/getting_reads/aligning_reads_against_genome.fasta/aligned_reads.bam.sorted.tmp.checking_correct_insertSizes/aligned_reads.bam.sorted.CollectInsertSizeMetrics.out.tmp > ./installation/test_installation/testing_outputs/read_trimmingCglab/getting_available_threads/genome.fasta_simulating_reads/getting_reads/aligning_reads_against_genome.fasta/aligned_reads.bam.sorted.tmp.checking_correct_insertSizes/aligned_reads.bam.sorted.CollectInsertSizeMetrics.out.tmp.generating.std 2>&1
 did not finish correctly. Out status: 32512

ERROR!!! Out status: 256
Traceback (most recent call last):
  File "./installation/test_installation/test_installation_modules.py", line 115, in <module>
    if fun.file_is_empty("%s/perSVade_finished_file.txt"%outdir_trimmed_reads): fun.run_cmd("%s trim_reads_and_QC --threads %i --fraction_available_mem 1.0 -f1 %s -f2 %s -o %s"%(fun.perSVade_modules, threads, cglab_reads1, cglab_reads2, outdir_trimmed_reads))
  File "./installation/test_installation/../../scripts/sv_functions.py", line 692, in run_cmd
    if out_stat!=0: raise ValueError("\n%s\n did not finish correctly. Out status: %i"%(cmd_to_run, out_stat))
ValueError: 
source //crex/proj/snic2020-2-19/private/darwins_finches/users/seba/BIN/etc/profile.d/conda.sh && conda activate persvuade > /dev/null 2>&1 && /crex/proj/snic2020-2-19/private/darwins_finches/users/seba/BIN/perSVade/installation/test_installation/../../scripts/perSVade trim_reads_and_QC --threads 40 --fraction_available_mem 1.0 -f1 ./installation/test_installation/testing_inputs/Cglabrata_reads/sampled_readsR1_first100k.fq.gz -f2 ./installation/test_installation/testing_inputs/Cglabrata_reads/sampled_readsR2_first100k.fq.gz -o ./installation/test_installation/testing_outputs/read_trimmingCglab
 did not finish correctly. Out status: 2560
######

Could you help me to understand what may have gone wrong? At which stage is this module installed?

Thanks in advance,
Matteo

**Comment by MikiSchikora** [comment]
Hi,

I am happy to see that the tool may be useful. It seems to be an issue with the persvuade_picard_env. The picard CollectInsertSizeMetrics seems not to be working. Can you provide the content of the file  ./installation/test_installation/testing_outputs/read_trimmingCglab/getting_available_threads/genome.fasta_simulating_reads/getting_reads/aligning_reads_against_genome.fasta/aligned_reads.bam.sorted.tmp.checking_correct_insertSizes/aligned_reads.bam.sorted.CollectInsertSizeMetrics.out.tmp.generating.std? With this I may be able to see what happened? 

Also, since this seems an installation issue, maybe derived because the conda-based installation is not the most reproducible, I'd generally recommend using the singularity image.

Best,
Miki

**Comment by MatteoSebastianelli** [comment]
Hi Miki, thanks for your response. I figured out the installation using singularity! As you mentioned, its way easier even for those who, like me, are not familiar with singularity!

Best,
Matteo

**Comment by MikiSchikora** [comment]
Hi,

Great, so this is solved now.

Best,
Miki
