### ISSUE TITLE
Pandas not installed in docker image

### ISSUE THREAD

**Issue by alistairhockey** [Gabaldonlab/perSVade#6]
Hi there,

I have noticed when trying to run perSVade inside the docker image that the prompt:

![Screenshot 2022-10-13 080819](https://user-images.githubusercontent.com/115673464/195469926-66b0aaab-d8be-4134-8221-3b33b5cdcd16.png)

I believe there isn't an issue outside of the docker, so maybe pandas has been installed in the incorrect place? I am using the most up-to-date version of perSVade with the help of @robsyme

Kind regards,
Alistair

**Comment by MikiSchikora** [comment]
Hi,

It seems that the conda environment perSVade_env (which contains pandas) is not activated in the interactive docker running. We developed the image to be run with `docker run -i mikischikora/persvade:<tag> scripts/perSVade`, so we did not consider such an interactive running. 

You can type `conda activate perSVade_env` before `/perSVade/scripts/perSVade`, and this should use de correct conda environment. Does this solve the issue?

Kind regards,

Miquel Àngel Schikora Tamarit

**Comment by alistairhockey** [comment]
Hi Miquel,

It works perfectly, thank you. Glad it was a simple issue to resolve.

Kind regards,
Alistair

**Comment by MikiSchikora** [comment]
Hi, 

Great. I am happy to see that it works!

Kind regards,

Miquel Àngel Schikora Tamarit
