### ISSUE TITLE
singularity exec  Hangup

### ISSUE THREAD

**Issue by xibeixingchen** [Gabaldonlab/perSVade#7]
Hi MikiSchikora,

There is a error about hangup:
code:  `singularity exec -e /home/jiazc/software/persvade.sif bash -c 'source /opt/conda/etc/profile.d/conda.sh && conda activate perSVade_env && python /perSVade/scripts/perSVade infer_repeats --ref /home/jiazc/work/alfalfa_genome/Muxu_Genome_Final.fasta --fraction_available_mem 0.3 -o /home/jiazc/work/persvade_output/repeat_inference'`
error: INFO:    Convert SIF file to sandbox...
INFO:    Cleaning up image...
Hangup

My RAM size is ~1TB, and refgenome size is ~800MB, 
[all_cmds.txt](https://github.com/Gabaldonlab/perSVade/files/9843566/all_cmds.txt)
, so what happened? 

Thanks,
Best

**Comment by MikiSchikora** [comment]
Hi,

If I understand correctly, and according to the all_cmds.txt you sent, the infer_repeats module worked until the run of RepeatModeler. Is this correct? Can you send me the STDOUT i STDERR of the running to debug the problem? If you re-run, could you add the `--verbose` argument?

I never saw this 'Hangup' message running singularity, so I wonder whether it is an error with perSVade's RepeatModeler running, which gets displayed like this in singularity.

I hope this helps,

Miquel Àngel Schikora

**Comment by xibeixingchen** [comment]
Hi Miquel,

I have uploaded debug the problem,
[repeatmodeler.std.txt](https://github.com/Gabaldonlab/perSVade/files/9845882/repeatmodeler.std.txt)

Thanks,
Best

**Comment by MikiSchikora** [comment]
Hi,

There seems to be no error in the repeat modeler std right?  In fact, this std suggests that the repeatmodeler run was interrupted, since it has no final 'success' message.  Can this be the case? Could you send perSVade's STDERR/STDOUT? This may clarify what happened.

Best,

Miquel Àngel Schikora

**Comment by xibeixingchen** [comment]
Hi,

I found  the repeatmodeler runing begain and sucessful, because other modeler simultaneous running

thank,
best
