### ISSUE TITLE
How to run a module multiple times at the same time?

### ISSUE THREAD

**Issue by xibeixingchen** [Gabaldonlab/perSVade#8]
Hi,

I have 186 sample, and want to run a module for each sample separately, such as call_small. This was supposed to speed things up. However, a new problem arises when multiple commands are executed and a new error is generated.  

INFO:    Convert SIF file to sandbox...
FATAL:   while extracting /home/jiazc/software/persvade.sif: root filesystem extraction failed: failed to copy content in staging file: write /tmp/archive-672565402: no space left on device

How can I solve this problem?

Best,
Thanks

**Comment by MikiSchikora** [comment]
Hi,

Could this be a disk space problem? Maybe removing  /tmp/archive-672565402 and re-running solves the issue? If not, maybe you need a computer with more disk. Can you send the full STDERR/STDOUT of one of perSVade's runs to debug?

Best,
Miquel Àngel Schikora

**Comment by xibeixingchen** [comment]
Hi,

Thank you for your professional answers, when I removed /tmp/archive-672565402 and re-running solves the issue. In addition, there does not seem to see full STDERR/STDOUT of one of perSVade's runs, I did not see it in the folder, it should run correctly. perSVade is now mounted under the /tpm/ , can I modify the mounted file through `singularity -B` ?

Thanks,
Best,
Zhicheng Jia

**Comment by MikiSchikora** [comment]
Hi,

Regarding the lack of STDERR/STDOUT for one run, I am not sure of what happened. I have seen that when there are disk errors some files get deleted or empty, which could explain it.

Regarding the mounting, I know that singularity mounts several folders automatically ($HOME and /tmp for sure). Maybe you could mount whatever folder (`<folder>`) as `/tmp` by adding `-B <folder>:/tmp`.

Best,
Miquel Àngel Schikora

**Comment by xibeixingchen** [comment]
Hi,

Thank your professional suggestion, I have solved this issue.

Thanks,
Best,
Zhicheng Jia
