### ISSUE TITLE
 root filesystem extraction failed: failed to copy content in staging file

### ISSUE THREAD

**Issue by xibeixingchen** [Gabaldonlab/perSVade#9]
Hi，

When I used code like`singularity exec -e /home/jiazc/work/persvade_output/persvade_v1.sif bash -c 'source /opt/conda/etc/profile.d/conda.sh && conda activate perSVade_env && python /perSVade/scripts/perSVade optimize_parameters --ref /home/jiazc/work/alfalfa_genome/Muxu_Genome_Final_filter.fasta -o /home/jiazc/work/persvade_output/parameter_optimization -sbam /home/jiazc/work/sort_bam/B195.sort.markdup.bam --mitochondrial_chromosome no_mitochondria --fraction_available_mem 0.6 --repeats_file /home/jiazc/work/persvade_output/repeat_inference/combined_repeats.tab --regions_SVsimulations /home/jiazc/work/persvade_output/find_hom_regions/breakpoints_aroundHomRegions_wsize=500bp_maxEval=1e-05_minQcovS=50.bedpe --max_coverage_sra_reads 30 --simulation_ploidies haploid'`, but a error is present.

INFO:    Converting SIF file to temporary sandbox...
FATAL:   while extracting /home/jiazc/work/persvade_output/persvade_v1.sif: root filesystem extraction failed: failed to copy content in staging file: write /tmp/rootfs-645513470/archive-2796493803: no space left on device

What should I do?

Thanks,
Best.

**Comment by MikiSchikora** [comment]
Hi,

It seems that you ran out of disk, is this possible? I have seen that when using custom regions for SV simulations (as you do) there may be a lot of intermediate files created, specially on large genomes. Can you send the full STDERR/STDOUT of perSVade to check it? If its a problem of filesystem, can you run this in another computer wiith more disk?

Going through your command I see this '--max_coverage_sra_reads' argument, which should not work on 'optimize_parameters'. Could removing this solve the issue?

Best,

Miquel Àngel Schikora

**Comment by xibeixingchen** [comment]
Hi,

Thank you for your professional answers. With your help, the problem has now been solved.

Thanks,
Best,
Zhicheng Jia
